# Generated by Django 4.2.1 on 2023-06-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("title", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=64)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=128)),
                ("theme", models.CharField(choices=[("T", "Technology"), ("L", "Life")], max_length=1)),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
